# Generated by Django 3.2.8 on 2021-10-15 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='nama_makanan',
            new_name='data_makanan',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='nama_minuman',
            new_name='data_minuman',
        ),
    ]
