# Generated by Django 3.2.8 on 2021-10-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Minuman',
        ),
        migrations.DeleteModel(
            name='pesanan',
        ),
        migrations.AlterField(
            model_name='makanan',
            name='jenis',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='makanan',
            name='nama',
            field=models.TextField(default='', max_length=30),
        ),
    ]
